### ISSUE TITLE
您好，请问代码中pos.py选取正例的方法和论文描述的是否有出入？

### ISSUE THREAD

**Issue by moonyeaL** [liun-online/HeCo#2]
以acm数据集为例，代码中pos.py选取正例时，load进来的pap和psp并没有表示两篇文章的在对应元路径下的连接条数，因为mp_gen.py生成的pap与psp只表示两篇paper是否有元路径相连，所以并没有考虑两篇文章的连接强度；但论文中说的是会根据两篇文章的多种元路径连接总数进行排序，然后选择具有最多元路径条数的5个点作为正例。也就是论文和代码在这里有些不一致，所以想请问您正例的选择方式到底应该是怎样的？

**Comment by liun-online** [comment]
在论文中的4.5节第二段，我们会先计算Ci(j)，如公式(10)。这个值是统计节点j在哪些元路径中，作为节点i的meta-path based neighbors出现过，此时并未考虑您提到的连接强度的问题，只是统计两个节点间有几种元路径相连。我们这么做是因为，如果考虑连接强度，即两个论文间具体有多少条元路径相连，那么PSP元路径会非常多；如果我们分别为PAP和PSP做归一化，再相加来统计强度，那么PSP的值会非常小。因此，我们只简单考虑元路径的种类。

正例的选取是一个重要的部分，如果您有更好的正例选取方式也值得尝试！

**Comment by moonyeaL** [comment]
> 在论文中的4.5节第二段，我们会先计算Ci(j)，如公式(10)。这个值是统计节点j在哪些元路径中，作为节点i的meta-path based neighbors出现过，此时并未考虑您提到的连接强度的问题，只是统计两个节点间有几种元路径相连。我们这么做是因为，如果考虑连接强度，即两个论文间具体有多少条元路径相连，那么PSP元路径会非常多；如果我们分别为PAP和PSP做归一化，再相加来统计强度，那么PSP的值会非常小。因此，我们只简单考虑元路径的种类。
> 
> 正例的选取是一个重要的部分，如果您有更好的正例选取方式也值得尝试！

噢，谢谢你，是我误解了文章的意思。
但是现在的方法也会有很多PSP元路径，我算了一下归一化的结果是差不多的。

**Comment by liun-online** [comment]
嗯嗯，您有好的正例选取方法可以进行更多的尝试，也欢迎继续交流！

**Comment by gau-nernst** [comment]
I have a related question. In pos.py, PAP and PSP meta-path-based adjacency matrices are row-normalized (same effect as dividing by out-degree) before adding up.

https://github.com/liun-online/HeCo/blob/20e8ca2042838877b2c815279920218b6bbea1db/data/pos.py#L23

Then I think Ci(j) calculation is not the same as Equation (10) in the paper? Equation 10 would suggest that there is no normalization, and the possible values for Ci(j) (for ACM dataset) would be 0, 1, or 2 (since there are 2 meta-paths in total). Are there any discrepancies between the code and Equation (10), or do I have a mistake in my understanding?

Thank you!

**Comment by liun-online** [comment]
Although there is a difference, I think the normalization here is not a severe question, which is just a small part to select positive neibors. You can have different choices if you want to try.

**Comment by gau-nernst** [comment]
Thank you for your reply! Although it is not the same as in the paper, I think the normalization makes sense since it will help the ranking/sorting of the neighbors. Without this normalization, the neighbors will only have Ci(j) = 1 or 2 in the case of ACM. It will be hard to differentiate the neighbors.
