### ISSUE TITLE
Model Framework Diagram

### ISSUE THREAD

**Issue by DuanhaoranCC** [liun-online/HeCo#9]
Hello dear author!

I just got started with heterogeneous graph neural network. I would like to ask you how to draw the model frame diagram. I have been using PPT all the time, but I don't know how to draw the heterogeneous graph.

Thank you very much for your patient guidance.

**Comment by liun-online** [comment]
Sorry, I am afraid that I cannot give you some practical opinions, since it depends on personal perception of aesthetic. For heterogeneous graph, you can just find some small icons to represent the object (e.g. a book icon to represent paper), or you just simply use circles with different colors to represent different kinds of objects. The edges between objects should be different, if they describe different relations.
